import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

export interface AffiliateReferralCode {
  id: string;
  affiliate_id: string;
  referral_code: string;
  created_at: string;
}

export interface PlatformReferral {
  id: string;
  referrer_id: string;
  referred_user_id: string;
  referral_code: string;
  commission_paid: boolean;
  commission_amount: number;
  created_at: string;
}

// Get or create affiliate referral code
export function useAffiliateReferralCode(affiliateId?: string) {
  return useQuery({
    queryKey: ["affiliate-referral-code", affiliateId],
    queryFn: async () => {
      if (!affiliateId) throw new Error("No affiliate ID");

      // Try to get existing code
      const { data: existing, error: fetchError } = await supabase
        .from("affiliate_referral_codes")
        .select("*")
        .eq("affiliate_id", affiliateId)
        .maybeSingle();

      if (fetchError) throw fetchError;

      if (existing) {
        return existing as AffiliateReferralCode;
      }

      // Create new code if none exists
      const { data: newCode, error: insertError } = await supabase
        .from("affiliate_referral_codes")
        .insert({ affiliate_id: affiliateId, referral_code: "" }) // referral_code will be auto-generated by trigger
        .select()
        .single();

      if (insertError) throw insertError;
      return newCode as AffiliateReferralCode;
    },
    enabled: !!affiliateId,
  });
}

// Get platform referrals for an affiliate
export function usePlatformReferrals(affiliateId?: string) {
  return useQuery({
    queryKey: ["platform-referrals", affiliateId],
    queryFn: async () => {
      if (!affiliateId) throw new Error("No affiliate ID");

      const { data, error } = await supabase
        .from("platform_referrals")
        .select("*")
        .eq("referrer_id", affiliateId)
        .order("created_at", { ascending: false });

      if (error) throw error;
      return data as PlatformReferral[];
    },
    enabled: !!affiliateId,
  });
}

// Validate referral code during registration
export async function validateReferralCode(code: string): Promise<{ valid: boolean; affiliateId?: string }> {
  const { data, error } = await supabase
    .from("affiliate_referral_codes")
    .select("affiliate_id")
    .eq("referral_code", code.toUpperCase())
    .maybeSingle();

  if (error || !data) {
    return { valid: false };
  }

  return { valid: true, affiliateId: data.affiliate_id };
}

// Record platform referral after registration
export async function recordPlatformReferral(
  referrerId: string,
  referredUserId: string,
  referralCode: string
): Promise<boolean> {
  const { error } = await supabase.from("platform_referrals").insert({
    referrer_id: referrerId,
    referred_user_id: referredUserId,
    referral_code: referralCode,
  });

  return !error;
}

// Get referred users with their profiles
export function useReferredUsers(affiliateId?: string) {
  return useQuery({
    queryKey: ["referred-users", affiliateId],
    queryFn: async () => {
      if (!affiliateId) throw new Error("No affiliate ID");

      const { data: referrals, error } = await supabase
        .from("platform_referrals")
        .select("*")
        .eq("referrer_id", affiliateId)
        .order("created_at", { ascending: false });

      if (error) throw error;

      // Get profiles for referred users
      const userIds = referrals.map((r) => r.referred_user_id);
      if (userIds.length === 0) return [];

      const { data: profiles } = await supabase
        .from("profiles")
        .select("id, full_name, email, created_at")
        .in("id", userIds);

      // Get roles for referred users
      const { data: roles } = await supabase
        .from("user_roles")
        .select("user_id, role")
        .in("user_id", userIds);

      return referrals.map((r) => ({
        ...r,
        profile: profiles?.find((p) => p.id === r.referred_user_id),
        roles: roles?.filter((role) => role.user_id === r.referred_user_id).map((role) => role.role) || [],
      }));
    },
    enabled: !!affiliateId,
  });
}
